"""xpymxpymbot

Revision ID: 2bcd53e28abe
Revises: c9e8a80b41b2
Create Date: 2023-10-19 10:12:00.418131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bcd53e28abe'
down_revision: Union[str, None] = 'c9e8a80b41b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tid', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'sid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
